export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    RESET_PASSWORD: "/auth/reset-password",
    FORGOT_PASSWORD: "/auth/forgot-password",
    CONFIRM_RESET_PASSWORD: "/auth/confirm-reset-password",
  },
  ITEMS: {
    GET_ALL: "/product/list",
    GET_BY_ID: (id: string) => `/product/${id}`,
    CREATE: "/product/create",
    UPDATE: (id: string) => `/product/update/${id}`,
    DELETE: (id: string) => `/product/delete/${id}`,
    CATEGORY_DROPDOWN: "/category/dropdown",
  },
  CATEGORIES: {
    GET_ALL: "/category/list",
    GET_BY_ID: (id: string) => `/category/${id}`,
    CREATE: "/category/create",
    UPDATE: (id: string) => `/category/update/${id}`,
    DELETE: (id: string) => `/category/delete/${id}`,
  },
  CUSTOMERS: {
    GET_ALL: "/user/list",
    DELETE: (id: string) => `/user/delete/${id}`,
  },
  CONTACTS: {
    GET_ALL: "/contact/list",
    CREATE: "/contact/create",
    GET_BY_ID: (id: string) => `/contact/${id}`,
    DELETE: (id: string) => `/contact/delete/${id}`,
    REPLY: (id: string) => `/contact/reply/${id}`,
  },
  REVIEWS: {
    GET_ALL: "/review/list",
    GET_BY_ID: (id: string) => `/review/${id}`,
    CREATE: "/review/create",
    DELETE: (id: string) => `/review/delete/${id}`,
  },
  COUPONS: {
    GET_ALL: "/coupon/list",
    AVAILABLE: "/coupon/available",
    GET_BY_ID: (id: string) => `/coupon/${id}`,
    CREATE: "/coupon/create",
    UPDATE: (id: string) => `/coupon/update/${id}`,
    DELETE: (id: string) => `/coupon/delete/${id}`,
  },
  DELIVERY_PERSON: {
    GET_ALL: "/delivery-person/list",
    GET_BY_ID: (id: string) => `/delivery-person/${id}`,
    CREATE: "/delivery-person/create",
    UPDATE: (id: string) => `/delivery-person/update/${id}`,
    DELETE: (id: string) => `/delivery-person/delete/${id}`,
  },
  BLOG: {
    GET_ALL: "/blog/list",
    GET_BY_ID: (id: string) => `/blog/${id}`,
    CREATE: "/blog/create",
    UPDATE: (id: string) => `/blog/update/${id}`,
    DELETE: (id: string) => `/blog/delete/${id}`,
  },
  USER_PROFILE: {
    GET_BY_ID: (id: string) => `/user/${id}`,
    UPDATE: (id: string) => `/user/update/${id}`,
  },
  CART: {
    CREATE: "/cart/create",
    CLEAR: "/cart/clear",
  },
  ORDER: {
    CREATE: "/order/create",
    LIST: "/order/list",
    DETAILS: (id: string) => `/order/details/${id}`,
    ADMIN_LIST: "/order/admin/list",
    ADMIN_ANALYTICS: "/order/admin/analytics",
    UPDATE_PAYMENT_STATUS: (id: string) => `/order/update-payment-status/${id}`,
    CANCEL: (id: string) => `/order/cancel/${id}`,
  },
  PAYMENT: {
    CREATE_ORDER: "/payment/create-order",
    VERIFY: "/payment/verify",
  },
  DELIVERY: {
    ASSIGN: "/delivery/assign",
    MY_DELIVERIES: "/delivery/my-deliveries",
    DETAILS: (id: string) => `/delivery/details/${id}`,
    UPDATE_STATUS: (id: string) => `/delivery/update-status/${id}`,
    TOGGLE_AVAILABILITY: "/delivery/toggle-availability",
    UPDATE_LOCATION: "/delivery/update-location",
    ADMIN_LIST: "/delivery/admin/list",
    ANALYTICS: "/delivery/analytics",
  },
};
